name: Build Meshcentral Unraid Image

on:
  push:
  schedule:
    - cron: "0 16 * * 6"

env:
  Mesh_V: 0

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout Meshcentral Repo
        uses: actions/checkout@v4
        with:
          repository: Ylianst/MeshCentral
          path: MeshCentral
      - name: Setup node and get Meshcentral version
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: echo "Mesh_V=$(npm show meshcentral version)" >> $GITHUB_ENV
      - run: echo $(ls -lah)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:docker_unraid/"
          push: true
          build-args: |
            UID=99
            GID=100
            PREINSTALL_LIBS=false
            INCLUDE_MONGODBTOOLS="yes"
            GITHUB_WORKSPACE=${{ env.GITHUB_WORKSPACE }}
          platforms: linux/amd64
          tags: |
            richy1989/meshcentral-dev:latest
            richy1989/meshcentral-dev:${{ env.Mesh_V }}