name: Build Meshcentral Unraid Image

on:
  push:

env:
  Mesh_V: 0

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: echo "Mesh_V=$(npm show meshcentral version)" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:builds/unraid/"
          push: true
          build-args: |
            UID=99
            GID=100
            PREINSTALL_LIBS=false
          platforms: linux/amd64
          tags: |
            richy1989/meshcentral:latest
            richy1989/meshcentral:${{ Mesh_V }}